# Generated by Django 5.0.4 on 2024-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='d_id',
        ),
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
