# Generated by Django 5.0.4 on 2024-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_remove_reg_d_id_alter_reg_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
