# Generated by Django 5.0.4 on 2024-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_signup_delete_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='D_id',
            field=models.IntegerField(default=10001, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
