# Generated by Django 5.0.4 on 2024-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_signup_d_id_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='D_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
