# Generated by Django 5.0.4 on 2024-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_signup_d_id_alter_signup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.IntegerField()),
                ('sub_id', models.IntegerField(unique=True)),
                ('code', models.TextField()),
            ],
        ),
    ]
