# Generated by Django 5.0.4 on 2024-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='code',
            field=models.CharField(max_length=1000000),
        ),
    ]
