# Generated by Django 5.0.4 on 2024-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_alter_submissions_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='D_id',
            field=models.IntegerField(default=1),
        ),
    ]
