# Generated by Django 5.0.4 on 2024-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_alter_submissions_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='D_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
