# Generated by Django 5.0.4 on 2024-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_alter_submissions_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='id',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
