# Generated by Django 5.0.4 on 2024-05-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_remove_submissions_id_alter_submissions_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='gemini_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
