# Generated by Django 5.0.4 on 2024-05-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_submissions_date_submissions_gemini_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='D_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
