# Generated by Django 5.0.4 on 2024-05-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0013_alter_signup_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='D_id',
            field=models.IntegerField(unique=True),
        ),
    ]
