# Generated by Django 5.0.4 on 2024-05-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_alter_signup_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='D_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
